root: true
env:
  browser: true
  es2022: true
  node: true
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: 'module'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
ignorePatterns:
  - node_modules
  - dist
